#!/usr/bin/env node
// Brand stamp: fetch the admin-configured brand from the running torch-server
// and emit packaging artifacts that white-label the desktop client + website.
//
// It does NOT mutate any Hermes core file. Instead it writes overrides into
// torch-packaging/out/ that the desktop build consumes via electron-builder's
// `-c.<key>=<value>` merge mechanism (which layers on top of the base `build`
// config in apps/desktop/package.json), plus a website brand JSON and a
// renderer .env for the API endpoint.
//
// Usage:
//   node torch-packaging/brand-stamp.mjs --server http://127.0.0.1:8080
//   node torch-packaging/brand-stamp.mjs --server https://api.example.com

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, 'out')

function arg(name, fallback) {
  const i = process.argv.indexOf(name)
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

const SERVER = arg('--server', 'http://127.0.0.1:8080').replace(/\/$/, '')

// Shell-quote a value for safe interpolation into the generated build script.
const sh = v => `'${String(v).replace(/'/g, `'\\''`)}'`

async function main() {
  const res = await fetch(`${SERVER}/brand`)
  if (!res.ok) {
    throw new Error(`GET ${SERVER}/brand -> ${res.status}`)
  }
  const b = await res.json()

  const displayName = b.app_display_name || b.app_name || 'Torch'
  const version = b.app_version || '0.1.0'
  const appId = b.bundle_id || 'com.torch.desktop'
  // ASCII-safe slug for installer filenames (display name may be non-ASCII).
  const asciiName = (b.app_name || 'Torch').replace(/[^A-Za-z0-9._-]+/g, '') || 'Torch'

  await mkdir(OUT, { recursive: true })

  // 1. Raw brand snapshot (audit / downstream reference).
  await writeFile(join(OUT, 'brand.json'), JSON.stringify(b, null, 2) + '\n')

  // 2. Website brand config — consumed by the download/landing site build.
  const website = {
    site_name: b.website_name || displayName,
    site_url: b.website_url || '',
    app_display_name: displayName,
    primary_color: b.primary_color || '#000000',
    support_email: b.support_email || '',
    download_url_mac: b.download_url_mac || '',
    download_url_win: b.download_url_win || '',
    app_icon_url: b.app_icon_url || ''
  }
  await writeFile(join(OUT, 'website-brand.json'), JSON.stringify(website, null, 2) + '\n')

  // 3. Renderer env — bakes the production API endpoint into the desktop build.
  await writeFile(join(OUT, 'desktop-build.env'), `VITE_TORCH_SERVER=${SERVER}\n`)

  // 4. electron-builder `-c` override args (merge onto apps/desktop package.json build).
  const overrides = {
    'appId': appId,
    'productName': displayName,
    // Keep electron-builder's own template tokens literal; only the name is ours.
    'artifactName': `${asciiName}-\${version}-\${os}-\${arch}.\${ext}`,
    'extraMetadata.version': version,
    'extraMetadata.productName': displayName,
    'mac.extendInfo.CFBundleDisplayName': displayName,
    'mac.extendInfo.CFBundleName': displayName
  }
  const builderArgs = Object.entries(overrides)
    .map(([k, v]) => `-c.${k}=${sh(v)}`)
    .join(' ')

  // 5. Ready-to-run desktop packaging script.
  const iconNote = b.app_icon_url
    ? `# Brand icon set: download ${b.app_icon_url} and replace apps/desktop/assets/icon.{png,icns,ico}\n`
    : `# No brand icon configured (app_icon_url empty) — using the default icon.\n`
  const buildScript =
    `#!/usr/bin/env bash\n` +
    `# Generated by torch-packaging/brand-stamp.mjs — white-labels the desktop client.\n` +
    `set -euo pipefail\n` +
    iconNote +
    `cd "$(dirname "$0")/../../apps/desktop"\n` +
    `export VITE_TORCH_SERVER=${sh(SERVER)}\n` +
    `# Build renderer + package with the brand overrides layered onto package.json "build".\n` +
    `npm run builder -- ${builderArgs}\n`
  await writeFile(join(OUT, 'build-desktop.sh'), buildScript, { mode: 0o755 })

  console.log(`Brand stamp written to ${OUT}`)
  console.log(`  app_display_name : ${displayName}`)
  console.log(`  app_version      : ${version}`)
  console.log(`  bundle_id        : ${appId}`)
  console.log(`  website_name     : ${website.site_name}`)
  console.log(`  api endpoint     : ${SERVER}`)
  console.log('')
  console.log('Artifacts:')
  console.log('  out/brand.json           full brand snapshot')
  console.log('  out/website-brand.json   website (landing/download) config')
  console.log('  out/desktop-build.env    renderer API endpoint')
  console.log('  out/build-desktop.sh     runnable desktop packaging command')
}

main().catch(e => {
  console.error(`brand-stamp failed: ${e.message}`)
  process.exit(1)
})
